export const skills = [
  {
    src: 'src/assets/JS.gif',
    width: 52,
    height: 52,
    alt: 'Native JS',
  },
  {
    src: 'src/assets/typescript.svg',
    width: 52,
    height: 52,
    alt: 'Typescript',
  },
  {
    src: 'src/assets/vue.svg',
    width: 56,
    height: 56,
    alt: 'Vue.js',
  },
  {
    // src: 'src/assets/vue-3-pinia.png',
    src: 'src/assets/vue-composition-api.svg',
    width: 48,
    height: 48,
    alt: 'Vue 3 (Composition API)',
  },
  {
    src: 'src/assets/nuxt.svg',
    width: 56,
    height: 56,
    alt: 'Nuxt.js',
  },
  {
    src: 'src/assets/swagger.svg',
    width: 64,
    height: 64,
    alt: 'Swagger',
  },
  {
    src: 'src/assets/postman.svg',
    width: 48,
    height: 48,
    alt: 'Postman',
  },
  {
    src: 'src/assets/git.svg',
    width: 48,
    height: 48,
    alt: 'Git',
  },
  {
    src: 'src/assets/npm.svg',
    width: 60,
    height: 20,
    alt: 'npm Registry',
  },
  {
    src: 'src/assets/github.svg',
    width: 48,
    height: 48,
    alt: 'Github',
  },
  {
    src: 'src/assets/indexedDB.png',
    width: 48,
    height: 48,
    alt: 'IndexedDB',
  },
  {
    // src: 'src/assets/web-workers.jpg',
    src: 'src/assets/web-workers.svg',
    width: 48,
    height: 48,
    alt: 'Web-workers',
  },
]
