export const sloganList = {
  eng: [
    'All comes from the Object which is Adam of all',
    'Funcs are our jam!',
    'Arrow functions are neutered kitties',
    'Funcs are the call girls',
    'The server`s not a cow, don`t pull its udder',
    'Funcs totally rule!',
    'See an object, look for constructor',
    'Only funcs have the balls',
    'Reference is a lockpick',
    'Users see pixels, front-enders - spot tags, but devs, man, they`re all about objects',
    'JS enters through the fingers',
  ],
  ua: [
    'Все походить від Object, який є Адамом усього',
    'Функції - ​це наше все!',
    'Стрілочні ​функції - це​ кастровані​ котики',
    'Функції - ​це дівчата​ за викликом',
    'Функції рулять!',
    'Тільки у ​функції ​є balls',
    "Бачиш об'єкт - шукай конструктор",
    'Посилання - це відмичка',
    "Юзер бачить ​пікселі, ​верстальник -​теги, а дев - об'єкти",
    "Сервер не корова, за вим'я не смикай",
    'JS заходить через пальці',
  ],
  ru: [
    'Все происходит от Object, который Адам всего',
    'Функции - наше все!',
    'Стрелочные ​функции - это​ кастрированные​ котики',
    'Функции - это девушки​ по вызову',
    'Функции рулят!',
    'Только у ​функции есть яйца',
    'Видишь объект - ищи конструктор',
    'Ссылка - это отмычка',
    'Юзер видит ​пиксели, ​верстальщик -​теги, а дев - объекты',
    'Сервер не корова, за вымя не дергай',
    'JS заходит через пальцы',
  ],
}
